#---------------------------------------------
# This is config file of tmux & tmux-powerline.
# Creator: Galimyanov Rustam # Applications: zsh, tmux, oh-my-zsh
# Platform: MacOS, WSL2 (current)
# Year: 2012-2025- ~
#---------------------------------------------
set -g default-command /opt/homebrew/bin/zsh
source-file ~/.tmux.base.conf
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
#set -g status-style bg=default
set-option -g status-position top
set -g mouse on
#setw -g mode-keys vi
set -g renumber-windows on   
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
set -g base-index 0
set -g history-limit 10000 
set -g detach-on-destroy off     # don't exit from tmux when closing a session set -g escape-time 0             # zero-out escape time delay
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
#setw -g automatic-rename off
#set-option -g allow-rename off
#set-option -g status on

# plugins
set -g @plugin 'TechnicalDC/tmux-ayu-theme'
set -g @plugin 'tmux-plugins/tmux-sidebar'
#set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @sessionx-bind 'o'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'

set -g @resurrect-capture-pane-contents 'on'

# Tmux sidebar settings
set -g @sidebar-tree-position 'right'
#set -g @sidebar-tree 'e'
#set -g @sidebar-tree-focus 'w'
set -g @sidebar-tree-pager 'view -'
set -g @sidebar-tree-width '60'
set -g @sidebar-tree-command 'tree -C'

# tmux-continuum options
set -g @continuum-boot 'on'
#set -g @continuum-boot-options 'iterm'
#set -g @continuum-boot-options 'fullscreen' 
set -g @continuum-restore 'on'

# tmux 1password options
# set -g @1password-key 'u'
set -g @1password-subdomain 'grk-family.1password.com'
set -g @1password-vault 'work_yukka'
set -g @1password-copy-to-clipboard 'on'

# tmux2k settings
# set the left and right plugin sections
#set -g @tmux2k-left-plugins "session cwd"
#set -g @tmux2k-right-plugins "battery cpu ram time"
#set -g @tmux2k-refresh-rate 5
#set -g @tmux2k-bg-main '#1f2430'
#set -g @tmux2k-theme 'onedark'

#set "@ayu_widgets" "#[fg=$ayu_yellow,bg=$ayu_black] $(basename $(pwd))"

run '~/.tmux/plugins/tpm/tpm'

run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
